### ISSUE TITLE
කේත හිමිකරු සම්බන්ධ කරගැනීම පිළිබඳවයි

### ISSUE THREAD

**Issue by aluyama** [para-d/si-wijesekara-keyboard#1]
මෙයට අදාළ මුල් ගැටළුවක් විසඳීම සඳහා ඔබගේ කේත භාවිතා කිරීමට අවශ්‍යව ඇත. නමුත් මෙම කෝෂ්ඨයට බලපත්‍රයක් යොදා නැති අතර අන් පාර්ශ්වයකට මෙහි අඩංගු කේත භාවිතා කළ හැකි ද?

**Comment by para-d** [comment]
@aluyama කැමති විදියකට පාවිච්චි කරන්න. ගැටළුවක් නෑ.

**Comment by para-d** [comment]
@aluyama බලපත්‍රයක් එකතු කළා

**Comment by aluyama** [comment]
@para-d ibus-m17n සහ xkb නවතම විජේසේකර යතුරුපුවරුවට **නිල වශයෙන්** යාවත්කාල කිරීම සඳහා කේතනයට සහාය වීමට හැකිද? කේතනයෙන් බාහිර කාර්යයන් සුළු දේවල් බැවින් මෙය තනිව සැකසීමට හැකියාවත් තිබේනම් සම්පූර්ණ ස්තූතිය (credit) ඔබට හිමිවනු ඇත. එමෙන්ම මෙය ස්වේච්ඡා දායකත්‍වයක් වන අතර දැනටමත් ප්‍රමාද බැවින් මාගේ ඉල්ලීම පිළිගෙන උදව් කිරීමට හැකිනම් බෙහෙවින් ස්තූතිවන්ත වෙමි.

ඔබගේ විද්‍යුත් තැපැල් ලිපිනයක් සොයා ගැනීමට උත්සාහ කළ ද හමු නොවිණි. අපගේ සාකච්ඡාව අතරතුර පෞද්ගලික දත්ත හුවමාරු විය හැකි බැවින් මෙම ලිපිනයට පණිවිඩයක් එවීමට හැකිද? aluyama@pm.me ඉන්පසු අපට ඒ හරහා කතාබහ කිරීමට හැකිය.
